version: "3.8"

services:
  bot:
    build:
      context: .
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
        WORKDIR: ${WORKDIR}
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    volumes:
      - ./${SECRET_DIR}/${SECRET_FILE}:/${SECRET_FILE}:ro
  db:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
